### ISSUE TITLE
Add support for RADOLAN data

### ISSUE THREAD

**Issue by amotl** [hiveeyes/dwdweather2#26]
Dear @mmaelicke,

within https://github.com/jlewis91/dwdbulk/issues/5, you asked for RADOLAN support. Most probably, reading the binary files would prove to be more efficient.

Integrating wradlib [2] or radproc [3] into `dwdweather2` should be possible, but would it make any sense? I am happy to receive any thoughts about this.

With kind regards,
Andreas.

[1] https://opendata.dwd.de/climate_environment/CDC/grids_germany/hourly/radolan/recent/bin/
[2] https://wradlib.org/
[3] https://github.com/jkreklow/radproc

**Comment by mmaelicke** [comment]
Hey Andreas,

For me personally, I can say that I implemented a quick&dirty script grabbing the RADOLAN data needed for analysis, which is not super complicated. The reason I asked was that the environment I am working in is a remote cluster and I usually prefer to build upon other packages that are maintained, as usually, it is exactly these scripts that screw up the toolchains.

I did not open an issue here, because fitting RADOLAN into the caching logic of `dwdweather2` would be quite a heavy lift, wouldn't it? 
I was not aware of wradlib, seems to be quite helpful, thanks for pointing out. 
A possible use-case, that I can see would be an interface to either of these two libraries, based on a list of stations (from the `observations_germany` branch). This might be a common use-case to first download meteorological data and then the RADOLAN covering the stations downloaded. Does that make sense?

Best, 
Mirko

**Comment by amotl** [comment]
Dear Mirko,

> For me personally, I can say that I implemented a quick&dirty script grabbing the RADOLAN data needed for analysis, which is not super complicated. The reason I asked was that the environment I am working in is a remote cluster and I usually prefer to build upon other packages that are maintained, as usually, it is exactly these scripts that screw up the toolchains.

I see. Been there, seen that ;]. Thanks for outlining your scenario.

> I did not open an issue here, because fitting RADOLAN into the caching logic of dwdweather2 would be quite a heavy lift, wouldn't it?

Well, it would definitively be some work, right.

> I was not aware of wradlib, seems to be quite helpful, thanks for pointing out.

You are welcome. I hope it will be useful to you.

> A possible use-case, that I can see would be an interface to either of these two libraries, based on a list of stations (from the observations_germany branch). This might be a common use-case to first download meteorological data and then the RADOLAN covering the stations downloaded. Does that make sense?

Absolutely. Thanks for outlining this. Let's keep this issue as a reference.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @mmaelicke,

thanks again for your input on this and for joining the discussion at https://github.com/earthobservations/wetterdienst/issues/71 already. Let's focus our efforts on [Wetterdienst](https://github.com/earthobservations/wetterdienst) instead of spending useless cycles with this library, right? So, I am deliberately closing the issue here.

With kind regards,
Andreas.
