### ISSUE TITLE
paths still correct? get no values...

### ISSUE THREAD

**Issue by michapr** [hiveeyes/dwdweather2#31]
Hi,

the paths are still correct?

I do not get daily data or hourly data for any station...

dwdweather weather 3987 2022-02-04T19:00

Messages like:
Station "3987" has no data for category "air_temperature"
Station "3987" has no data for category "cloud_type"
....

If I check https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/
then I see only directories "historical", "recent","timeseries_overview"  - but not "now"

I think something was there updated?

Thanks!

**Comment by amotl** [comment]
Dear Michael,

thank you for writing in. The `dwdweather2` library does not receive any maintenance these days, because @gutzbenj and me bundled our efforts into the `wetterdienst` framework [^1], which aims to be way more comprehensive and continuously maintained. We will be happy to welcome you as a new user over there. Please let us know about the outcome for you.

With kind regards,
Andreas.

[^1]: https://github.com/earthobservations/wetterdienst

P.S.: I've added a note about this with 01cba4cd2, but I believe I should emphasize this detail better, and set the repository on "archived" mode, in order to make this clearer.

**Comment by michapr** [comment]
Thanks for your answer, will check the wetterdienst framework ;)

Setting to archive mode - maybe with a link to the new project maybe a good idea ...

Will close it for now.
